### ISSUE TITLE
Debugging the project in Visual Studio

### ISSUE THREAD

**Issue by TomasHubelbauer** [noliar/ASP.NET-Core-Sample#1]
Hello, what can be done so that this project can be developed in Visual Studio and then tested with F5 debugger attached but also keep working when deployed to Heroku?

Currently deployment to Heroku works just fine, but even when doing a clean Git clone and running unchanged the F5 experience is a _connection reset_ screen. The `Main` method is not hit in the debugger.

Can these two scenarios be reconciled so that when developing locally LocalDB (or SQLite, doesn't really matter) is used and when deploying, SQLite is used as it is now?

**Comment by noliar** [comment]
ah...It may be a bug of Visual Studio tool?

 If I set the `outputName`, I cannot debug and visit website through `IIS Express`. Without `outputName`, it works well.

For now, the project is worked with SQLite. I think the better way may is using Postgres when deploying, because we [overlay](https://github.com/noliar/ASP.NET-Core-Sample/blob/master/MyMvc/project.json#L91) the db(SQLite) file when publishing which will lose data.

**Comment by TomasHubelbauer** [comment]
Interesting, I've removed `outputName` completely and it now works both locally and remotely. Out of curiosity, why was `outputName` used when it works without it? For "aesthetics" (for lack of a better word)? I've noticed the solution is named `cli-samples` when the project is called `MyMvc` so perhaps it was renamed during development and that is the reason?

As far as databases go, I've decided to keep SQLite both locally and remotely because it seems to work well out of the bix and I will try developing with it. Thank you for your help.
