### ISSUE TITLE
Unable to deploy this sample project.

### ISSUE THREAD

**Issue by sousousore1** [noliar/ASP.NET-Core-Sample#2]
Hello.
Now, I'm trying to deploy this sample project to Heroku from heroku button on README.
But I'm occurs Application Error when open the app.
(By the way Deployment seems to be succeed.)
what's wrong?

Thanks.

**Comment by noliar** [comment]
Because `.NET Core SDK Binaries` new preview was released several days ago, which cause the version in preview channel changed to `1.0.0-preview2.1-003155`.  So temp [fix](https://github.com/noliar/ASP.NET-Core-Sample/commit/3bc69edcab0fc34d10a35ce69c79dfd7bc54d0cd) is adding a `global.json` to specify the version of sdk, like '1.0.0-preview2-003121'.

**Comment by sousousore1** [comment]
Thanks!!
I was able to be fixed by your advice.
